# Defines a list of files that are part of main custom_component of Home Assistant.
# Changes to these files/filters define how our CI test suite is ran.
core: &core
  - custom_components\sax_battery_ha\**
  - pyproject.toml
  - requirements.txt

